version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::732499942675:user/aws-sam-cli-managed-dev-lin-pipeline-PipelineUser-1VHB9FH2PN4C5"

[dev-lin]
[dev-lin.pipeline_bootstrap]
[dev-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1CENO9XYIXMUB"
cloudformation_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-I28L3Z0EQUIP"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-eiif4khf11se"
image_repository = ""
region = "us-east-1"

[prod-lin]
[prod-lin.pipeline_bootstrap]
[prod-lin.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1CENO9XYIXMUB"
cloudformation_execution_role = "arn:aws:iam::732499942675:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-I28L3Z0EQUIP"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-eiif4khf11se"
image_repository = ""
region = "us-east-1"
