version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::746606725297:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-113YE10GI9PZM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-47016RGZFK1"
cloudformation_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1ET2OQ1IVWYSA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1cdyv6aqzxhaj"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-O3EU8SYSJPVK"
cloudformation_execution_role = "arn:aws:iam::746606725297:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-4ZR4CFMUMN3K"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-n2ca44jgrpvj"
image_repository = ""
region = "us-east-1"
