version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # trigger the unit tests here
      - echo 'Running unit tests'
      - pip install --upgrade pip
      - pip install -r tests/requirements.txt
      - python -m pytest ./tests/unit -v
      - echo 'unit tests done'
