version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # trigger the unit tests here
      - pip install --upgrade pip
      - pip install pytest
      - pwd
      - echo 'Running unit tests'
      - python -m pytest
